let rsMapping = {
  0: "Overall",
  1: "Attack",
  2: "Defence",
  3: "Strength",
  4: "Hitpoints",
  5: "Ranged",
  6: "Prayer",
  7: "Magic",
  8: "Cooking",
  9: "Woodcutting",
  10: "Fletching",
  11: "Fishing",
  12: "Firemaking",
  13: "Crafting",
  14: "Smithing",
  15: "Mining",
  16: "Herblore",
  17: "Agility",
  18: "Thieving",
  19: "Slayer",
  20: "Farming",
  21: "Runecrafting",
  22: "Hunter",
  23: "Construction",
  24: "League Points",
  25: "Bounty Hunter - Hunter",
  26: "Bounty Hunter - Rogue",
  27: "Clue Scrolls (all)",
  28: "Clue Scrolls (beginner)",
  29: "Clue Scrolls (easy)",
  30: "Clue Scrolls (medium)",
  31: "Clue Scrolls (hard)",
  32: "Clue Scrolls (elite)",
  33: "Clue Scrolls (master)",
  34: "LMS - Rank",
  35: "Soul Wars Zeal",
  36: "Abyssal Sire",
  37: "Alchemical Hydra",
  38: "Barrows Chests",
  39: "Bryophyta",
  40: "Callisto",
  41: "Cerberus",
  42: "Chambers of Xeric",
  43: "Chambers of Xeric: Challenge Mode",
  44: "Chaos Elemental",
  45: "Chaos Fanatic",
  46: "Commander Zilyana",
  47: "Corporeal Beast",
  48: "Crazy Archaeologist",
  49: "Dagannoth Prime",
  50: "Dagannoth Rex",
  51: "Dagannoth Supreme",
  52: "Deranged Archaeologist",
  53: "General Graardor",
  54: "Giant Mole",
  55: "Grotesque Guardians",
  56: "Hespori",
  57: "Kalphite Queen",
  58: "King Black Dragon",
  59: "Kraken",
  60: "Kree'Arra",
  61: "K'ril Tsutsaroth",
  62: "Mimic",
  63: "Nightmare",
  64: "Obor",
  65: "Sarachnis",
  66: "Scorpia",
  67: "Skotizo",
  68: "Tempoross",
  69: "The Gauntlet",
  70: "The Corrupted Gauntlet",
  71: "Theatre of Blood",
  72: "Theatre of Blood: Hard Mode",
  73: "Thermonuclear Smoke Devil",
  74: "TzKal-Zuk",
  75: "TzTok-Jad",
  76: "Venenatis",
  77: "Vet'ion",
  78: "Vorkath",
  79: "Unknown",
  80: "Wintertodt",
  81: "Zalcano",
  82: "Zulrah",
};

module.exports = {
  rsMapping,
};
